// =============================================================================
// AppointmentReminderPreference.cs — Scaffolded from SQL Server
// [AppointmentReminderPreference] table.
//
// Generated by EF Core Database-First (Scaffold-DbContext).
// Column/table mapping is in AppointmentDbContext.OnModelCreating().
// =============================================================================

namespace AppointmentBooking.Models
{
    /// <summary>
    /// Per-customer reminder preferences (one row per customer, UNIQUE on CustomerId).
    /// Mapped to dbo.AppointmentReminderPreference.
    /// </summary>
    public partial class AppointmentReminderPreference
    {
        // ── Scalar columns ────────────────────────────────────────────────────

        /// <summary>Primary key — identity column.</summary>
        public int PreferenceId { get; set; }

        /// <summary>Customer identifier (NOT NULL, UNIQUE, max 100 chars).</summary>
        public string CustomerId { get; set; } = null!;

        /// <summary>How many days before the appointment to send a reminder (default 1).</summary>
        public int ReminderDaysBefore { get; set; }

        /// <summary>How many hours before the appointment to send a reminder (default 2).</summary>
        public int ReminderHourBefore { get; set; }

        /// <summary>Whether to send email reminders (default true).</summary>
        public bool EnableEmailReminder { get; set; }

        /// <summary>Whether to send SMS reminders (default false).</summary>
        public bool EnableSmsReminder { get; set; }

        /// <summary>Row creation timestamp.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>Last-update timestamp.</summary>
        public DateTime? UpdatedAt { get; set; }
    }
}
