// =============================================================================
// AppointmentBooking.cs — Scaffolded from SQL Server [AppointmentBooking] table.
//
// Generated by EF Core Database-First (Scaffold-DbContext).
// All column/table mapping is in AppointmentDbContext.OnModelCreating().
// =============================================================================

namespace AppointmentBooking.Models
{
    /// <summary>
    /// A customer's appointment booking against a specific time-slot.
    /// Mapped to dbo.AppointmentBooking.
    /// </summary>
    public partial class AppointmentBooking
    {
        // ── Scalar columns ────────────────────────────────────────────────────

        /// <summary>Primary key — identity column.</summary>
        public int BookingId { get; set; }

        /// <summary>Human-readable booking reference, e.g. APT-2026-000001 (UNIQUE).</summary>
        public string BookingNumber { get; set; } = null!;

        /// <summary>Nullable — guest bookings may not have a customer ID.</summary>
        public string? CustomerId { get; set; }

        /// <summary>FK → AppointmentSlot.SlotId.</summary>
        public int SlotId { get; set; }

        /// <summary>Customer first name (NOT NULL, max 100).</summary>
        public string FirstName { get; set; } = null!;

        /// <summary>Customer last name (NOT NULL, max 100).</summary>
        public string LastName { get; set; } = null!;

        /// <summary>Customer email address (NOT NULL, max 200).</summary>
        public string Email { get; set; } = null!;

        /// <summary>Customer phone number (NOT NULL, max 20).</summary>
        public string PhoneNumber { get; set; } = null!;

        /// <summary>Type: Consultation | Viewing | Purchase | Other (default Consultation).</summary>
        public string AppointmentType { get; set; } = null!;

        /// <summary>Optional notes from the customer (max 1000 chars).</summary>
        public string? Notes { get; set; }

        /// <summary>Lifecycle status: Pending | Confirmed | Completed | Cancelled | NoShow.</summary>
        public string BookingStatus { get; set; } = null!;

        /// <summary>True after a reminder has been sent for this booking.</summary>
        public bool ReminderSent { get; set; }

        /// <summary>UTC timestamp when the reminder was dispatched.</summary>
        public DateTime? ReminderSentAt { get; set; }

        /// <summary>Row creation timestamp.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>Last-update timestamp.</summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>User who created this booking.</summary>
        public string? CreatedBy { get; set; }

        /// <summary>User who last updated this booking.</summary>
        public string? UpdatedBy { get; set; }

        // ── Navigation properties ─────────────────────────────────────────────

        /// <summary>The time-slot this booking is assigned to.</summary>
        public virtual AppointmentSlot Slot { get; set; } = null!;

        /// <summary>Optional post-appointment feedback (1-to-1).</summary>
        public virtual AppointmentFeedback? Feedback { get; set; }
    }
}
