// =============================================================================
// AppointmentSlot.cs — Scaffolded from SQL Server [AppointmentSlot] table.
//
// Generated by EF Core Database-First (Scaffold-DbContext).
// Column/table mapping is defined in AppointmentDbContext.OnModelCreating().
// Custom business logic (RefreshStatus) lives in this partial class because
// it does not affect the DB schema and won't be overwritten by re-scaffolding.
// =============================================================================

namespace AppointmentBooking.Models
{
    /// <summary>
    /// A bookable time-slot within a section on a specific date.
    /// Mapped to dbo.AppointmentSlot.
    /// </summary>
    public partial class AppointmentSlot
    {
        // ── Scalar columns ────────────────────────────────────────────────────

        /// <summary>Primary key — identity column.</summary>
        public int SlotId { get; set; }

        /// <summary>FK → AppointmentSection.SectionId.</summary>
        public int SectionId { get; set; }

        /// <summary>Calendar date of this slot (DATE in SQL).</summary>
        public DateOnly SlotDate { get; set; }

        /// <summary>Slot start time (TIME in SQL).</summary>
        public TimeOnly StartTime { get; set; }

        /// <summary>Slot end time (TIME in SQL).</summary>
        public TimeOnly EndTime { get; set; }

        /// <summary>Maximum number of concurrent bookings for this slot.</summary>
        public int TotalCapacity { get; set; }

        /// <summary>Current number of confirmed bookings against this slot.</summary>
        public int BookedCount { get; set; }

        /// <summary>
        /// Computed property (NOT mapped to DB) — how many more bookings this
        /// slot can accept. In SQL this is a persisted computed column but EF
        /// Core ignores it (configured in OnModelCreating).
        /// </summary>
        public int AvailableCapacity => TotalCapacity - BookedCount;

        /// <summary>Current status: Available | Limited | Full | Blocked | Completed.</summary>
        public string SlotStatus { get; set; } = null!;

        /// <summary>Hex colour used by the frontend slot-selector UI.</summary>
        public string? ColorCode { get; set; }

        /// <summary>True when an admin has manually blocked this slot.</summary>
        public bool IsBlocked { get; set; }

        /// <summary>Reason the admin blocked the slot (max 500 chars).</summary>
        public string? BlockReason { get; set; }

        /// <summary>Row creation timestamp.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>Last-update timestamp.</summary>
        public DateTime? UpdatedAt { get; set; }

        // ── Navigation properties ─────────────────────────────────────────────

        /// <summary>Parent section this slot belongs to.</summary>
        public virtual AppointmentSection Section { get; set; } = null!;

        /// <summary>All bookings made against this slot.</summary>
        public virtual ICollection<AppointmentBooking> Bookings { get; set; } = new List<AppointmentBooking>();

        // ── Business logic ────────────────────────────────────────────────────

        /// <summary>
        /// Recalculates SlotStatus and ColorCode based on current availability.
        /// Call this after changing BookedCount or IsBlocked so the denormalised
        /// status columns stay consistent before SaveChangesAsync().
        /// </summary>
        public void RefreshStatus()
        {
            if (IsBlocked)
            {
                SlotStatus = "Blocked";
                ColorCode = "#6b7280"; // gray-500
                return;
            }

            if (AvailableCapacity <= 0)
            {
                SlotStatus = "Full";
                ColorCode = "#ef4444"; // red-500
                return;
            }

            var ratio = (double)AvailableCapacity / TotalCapacity;
            if (ratio > 0.5)
            {
                SlotStatus = "Available";
                ColorCode = "#22c55e"; // green-500
            }
            else
            {
                SlotStatus = "Limited";
                ColorCode = "#eab308"; // yellow-500
            }
        }
    }
}
