// =============================================================================
// AppointmentSection.cs — Scaffolded from SQL Server [AppointmentSection] table.
//
// This model was generated by EF Core Database-First tooling (Scaffold-DbContext).
// DO NOT add data annotations here; all column/table mapping lives in
// AppointmentDbContext.OnModelCreating() so the schema stays in one place.
//
// If you need to add custom logic, create a separate partial-class file
// (e.g. AppointmentSection.Custom.cs) so re-scaffolding won't overwrite it.
// =============================================================================

namespace AppointmentBooking.Models
{
    /// <summary>
    /// Represents a showroom section (e.g. Kitchen &amp; Dining, Living Room).
    /// Mapped to dbo.AppointmentSection.
    /// </summary>
    public partial class AppointmentSection
    {
        // ── Scalar columns ────────────────────────────────────────────────────

        /// <summary>Primary key — identity column in SQL Server.</summary>
        public int SectionId { get; set; }

        /// <summary>Display name of the section (max 100 chars, NOT NULL).</summary>
        public string SectionName { get; set; } = null!;

        /// <summary>Optional description (max 500 chars).</summary>
        public string? Description { get; set; }

        /// <summary>Physical location inside the showroom (max 200 chars).</summary>
        public string? Location { get; set; }

        /// <summary>CDN URL for the section image (max 500 chars).</summary>
        public string? ImageUrl { get; set; }

        /// <summary>Soft-delete flag. False = hidden from public listings.</summary>
        public bool IsActive { get; set; }

        /// <summary>Row creation timestamp (DEFAULT GETUTCDATE() in SQL).</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>Last-update timestamp — set by application code.</summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>Username/ID of the creator (max 100 chars).</summary>
        public string? CreatedBy { get; set; }

        /// <summary>Username/ID of the last updater (max 100 chars).</summary>
        public string? UpdatedBy { get; set; }

        // ── Navigation properties ─────────────────────────────────────────────
        // EF Core populates these when you use .Include() in LINQ queries.

        /// <summary>All time-slots belonging to this section.</summary>
        public virtual ICollection<AppointmentSlot> Slots { get; set; } = new List<AppointmentSlot>();

        /// <summary>Capacity rules that govern slot generation for this section.</summary>
        public virtual ICollection<AppointmentCapacity> Capacities { get; set; } = new List<AppointmentCapacity>();

        /// <summary>Weekly operating-hours schedule for this section.</summary>
        public virtual ICollection<AppointmentOperatingHours> OperatingHours { get; set; } = new List<AppointmentOperatingHours>();
    }
}
