// =============================================================================
// AppointmentFeedback.cs — Scaffolded from SQL Server [AppointmentFeedback] table.
//
// Generated by EF Core Database-First (Scaffold-DbContext).
// Column/table mapping is in AppointmentDbContext.OnModelCreating().
// =============================================================================

namespace AppointmentBooking.Models
{
    /// <summary>
    /// Post-appointment feedback / rating (one per booking).
    /// Mapped to dbo.AppointmentFeedback.
    /// </summary>
    public partial class AppointmentFeedback
    {
        // ── Scalar columns ────────────────────────────────────────────────────

        /// <summary>Primary key — identity column.</summary>
        public int FeedbackId { get; set; }

        /// <summary>FK → AppointmentBooking.BookingId (one-to-one).</summary>
        public int BookingId { get; set; }

        /// <summary>Star rating 1–5.</summary>
        public byte Rating { get; set; }

        /// <summary>Optional text comment (max 1000 chars).</summary>
        public string? Comment { get; set; }

        /// <summary>Row creation timestamp.</summary>
        public DateTime CreatedAt { get; set; }

        // ── Navigation properties ─────────────────────────────────────────────

        /// <summary>The booking this feedback belongs to.</summary>
        public virtual AppointmentBooking Booking { get; set; } = null!;
    }
}
