// =============================================================================
// AppointmentCapacity.cs — Scaffolded from SQL Server [AppointmentCapacity] table.
//
// Generated by EF Core Database-First (Scaffold-DbContext).
// Column/table mapping is in AppointmentDbContext.OnModelCreating().
// =============================================================================

namespace AppointmentBooking.Models
{
    /// <summary>
    /// Defines how many salespersons are available for a given section, day/date,
    /// and hour — used by SlotGenerationService to create AppointmentSlot rows.
    /// Mapped to dbo.AppointmentCapacity.
    /// </summary>
    public partial class AppointmentCapacity
    {
        // ── Scalar columns ────────────────────────────────────────────────────

        /// <summary>Primary key — identity column.</summary>
        public int CapacityId { get; set; }

        /// <summary>FK → AppointmentSection.SectionId.</summary>
        public int SectionId { get; set; }

        /// <summary>0 = Sunday … 6 = Saturday. NULL when SpecificDate is set.</summary>
        public byte? DayOfWeek { get; set; }

        /// <summary>Overrides DayOfWeek for a one-off date (e.g. a holiday).</summary>
        public DateOnly? SpecificDate { get; set; }

        /// <summary>Hour of the day (0–23) this rule applies to.</summary>
        public byte HourOfDay { get; set; }

        /// <summary>Number of salespersons available during this hour (1–50).</summary>
        public byte SalespersonCount { get; set; }

        /// <summary>Duration of each appointment slot in minutes (5–240, default 30).</summary>
        public byte AppointmentDurationMinutes { get; set; }

        /// <summary>
        /// Computed property (NOT mapped to DB) — how many slots fit within one hour.
        /// In SQL this is a persisted computed column; EF Core ignores it
        /// (configured via .Ignore() in OnModelCreating).
        /// </summary>
        public int SlotsPerHour => AppointmentDurationMinutes > 0
            ? 60 / AppointmentDurationMinutes
            : 0;

        /// <summary>Whether this rule is active. Inactive rules are skipped during slot generation.</summary>
        public bool IsActive { get; set; }

        /// <summary>Row creation timestamp.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>Last-update timestamp.</summary>
        public DateTime? UpdatedAt { get; set; }

        // ── Navigation properties ─────────────────────────────────────────────

        /// <summary>Parent section this capacity rule belongs to.</summary>
        public virtual AppointmentSection Section { get; set; } = null!;
    }
}
