// =============================================================================
// AppointmentOperatingHours.cs — Scaffolded from SQL Server [AppointmentOperatingHours].
//
// Generated by EF Core Database-First (Scaffold-DbContext).
// Column/table mapping is in AppointmentDbContext.OnModelCreating().
// =============================================================================

namespace AppointmentBooking.Models
{
    /// <summary>
    /// Weekly operating-hours schedule for a section (one row per day-of-week).
    /// Mapped to dbo.AppointmentOperatingHours.
    /// </summary>
    public partial class AppointmentOperatingHours
    {
        // ── Scalar columns ────────────────────────────────────────────────────

        /// <summary>Primary key — identity column.</summary>
        public int HoursId { get; set; }

        /// <summary>FK → AppointmentSection.SectionId.</summary>
        public int SectionId { get; set; }

        /// <summary>0 = Sunday … 6 = Saturday.</summary>
        public byte DayOfWeek { get; set; }

        /// <summary>Opening time for this day (TIME in SQL).</summary>
        public TimeOnly OpeningTime { get; set; }

        /// <summary>Closing time for this day (TIME in SQL).</summary>
        public TimeOnly ClosingTime { get; set; }

        /// <summary>True if the section is closed on this day of the week.</summary>
        public bool IsClosed { get; set; }

        /// <summary>Row creation timestamp.</summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>Last-update timestamp.</summary>
        public DateTime? UpdatedAt { get; set; }

        // ── Navigation properties ─────────────────────────────────────────────

        /// <summary>Parent section this schedule belongs to.</summary>
        public virtual AppointmentSection Section { get; set; } = null!;
    }
}
