/**
 * Migration: 001_initial_schema
 *
 * Creates all tables required for the Appointment Booking module.
 *
 * Tables
 * ──────
 * sections            – Store sections (Kitchen, Wardrobe, Tiles, etc.)
 * section_schedules   – Operating hours per section per day-of-week
 * section_capacity    – Salesperson count per section per date-hour slot
 * appointment_slots   – Auto-generated bookable slots (1 row = 1 hour window)
 * appointments        – Customer bookings
 * appointment_feedback– Post-visit ratings & comments
 * notification_templates – SMS / email / push templates
 * notification_log    – Outbound notification audit trail
 */

exports.up = async (knex) => {
  // ── sections ──────────────────────────────────────────────────────────────
  await knex.schema.createTable('sections', (t) => {
    t.increments('id').primary()
    t.string('name', 100).notNullable().unique()
    t.string('slug', 100).notNullable().unique()
    t.text('description')
    t.string('location', 255)
    t.string('icon_url', 500)
    t.string('image_url', 500)
    t.integer('appointment_duration_minutes').defaultTo(60)
      .comment('Duration of a single appointment slot in minutes')
    t.boolean('is_active').defaultTo(true)
    t.timestamps(true, true) // created_at, updated_at
  })

  // ── section_schedules ─────────────────────────────────────────────────────
  // Defines operating hours for each section per day of the week.
  // day_of_week: 0=Sunday … 6=Saturday
  await knex.schema.createTable('section_schedules', (t) => {
    t.increments('id').primary()
    t.integer('section_id').unsigned().notNullable()
      .references('id').inTable('sections').onDelete('CASCADE')
    t.integer('day_of_week').notNullable().comment('0=Sun, 1=Mon … 6=Sat')
    t.time('open_time').notNullable().defaultTo('10:00')
    t.time('close_time').notNullable().defaultTo('19:00')
    t.boolean('is_open').defaultTo(true)
    t.unique(['section_id', 'day_of_week'])
    t.timestamps(true, true)
  })

  // ── section_capacity ──────────────────────────────────────────────────────
  // Configures how many salespersons are available for a specific section on
  // a specific date (overrides the default capacity set on the section).
  await knex.schema.createTable('section_capacity', (t) => {
    t.increments('id').primary()
    t.integer('section_id').unsigned().notNullable()
      .references('id').inTable('sections').onDelete('CASCADE')
    t.date('date').notNullable()
    t.time('hour_start').notNullable().comment('Start of the hour, e.g. 10:00')
    t.integer('salesperson_count').notNullable().defaultTo(1)
    t.unique(['section_id', 'date', 'hour_start'])
    t.timestamps(true, true)
  })

  // ── appointment_slots ─────────────────────────────────────────────────────
  // Each row represents one bookable hour-window for a section.
  // Slots are auto-generated by the slot generator utility.
  await knex.schema.createTable('appointment_slots', (t) => {
    t.increments('id').primary()
    t.integer('section_id').unsigned().notNullable()
      .references('id').inTable('sections').onDelete('CASCADE')
    t.date('date').notNullable()
    t.time('start_time').notNullable()
    t.time('end_time').notNullable()
    t.integer('max_bookings').notNullable().defaultTo(1)
      .comment('Derived from salesperson_count')
    t.integer('current_bookings').defaultTo(0)
    t.enum('status', ['available', 'full', 'blocked']).defaultTo('available')
    t.unique(['section_id', 'date', 'start_time'])
    t.timestamps(true, true)
  })

  // ── appointments ──────────────────────────────────────────────────────────
  await knex.schema.createTable('appointments', (t) => {
    t.increments('id').primary()
    t.string('booking_id', 20).notNullable().unique()
      .comment('Human-readable booking reference, e.g. APT-20240402-0001')
    t.integer('slot_id').unsigned().notNullable()
      .references('id').inTable('appointment_slots').onDelete('RESTRICT')
    t.integer('section_id').unsigned().notNullable()
      .references('id').inTable('sections').onDelete('RESTRICT')
    // Customer details (denormalised for easy look-up)
    t.string('user_id', 100)
    t.string('user_name', 200).notNullable()
    t.string('user_email', 200).notNullable()
    t.string('user_phone', 30).notNullable()
    // Appointment time
    t.date('appointment_date').notNullable()
    t.time('appointment_time').notNullable()
    t.enum('status', [
      'Pending',
      'Schedule',
      'Reschedule',
      'In-Discussion',
      'Completed',
      'Cancelled',
      'No-Show'
    ]).defaultTo('Pending')
    t.text('notes').comment('Internal admin notes')
    t.boolean('is_vip').defaultTo(false).comment('Force-booked VIP slot')
    t.string('cancelled_by', 50).comment('"customer" or "admin"')
    t.text('cancellation_reason')
    t.timestamps(true, true)
  })

  // ── appointment_feedback ──────────────────────────────────────────────────
  await knex.schema.createTable('appointment_feedback', (t) => {
    t.increments('id').primary()
    t.integer('appointment_id').unsigned().notNullable()
      .references('id').inTable('appointments').onDelete('CASCADE')
    t.integer('rating').unsigned().comment('1–5 stars')
    t.text('comment')
    t.timestamps(true, true)
  })

  // ── notification_templates ────────────────────────────────────────────────
  await knex.schema.createTable('notification_templates', (t) => {
    t.increments('id').primary()
    t.string('name', 100).notNullable().unique()
      .comment('e.g. "booking_confirmation", "reminder_24h"')
    t.enum('channel', ['email', 'sms', 'push']).notNullable()
    t.string('subject', 255).comment('Email subject line')
    t.text('body').notNullable()
      .comment('Template body – use {{variable}} placeholders')
    t.boolean('is_active').defaultTo(true)
    t.timestamps(true, true)
  })

  // ── notification_log ──────────────────────────────────────────────────────
  await knex.schema.createTable('notification_log', (t) => {
    t.increments('id').primary()
    t.integer('appointment_id').unsigned()
      .references('id').inTable('appointments').onDelete('SET NULL')
    t.integer('template_id').unsigned()
      .references('id').inTable('notification_templates').onDelete('SET NULL')
    t.enum('channel', ['email', 'sms', 'push']).notNullable()
    t.string('recipient', 255).notNullable()
    t.enum('status', ['pending', 'sent', 'failed']).defaultTo('pending')
    t.text('error_message')
    t.timestamp('sent_at')
    t.timestamps(true, true)
  })
}

exports.down = async (knex) => {
  await knex.schema.dropTableIfExists('notification_log')
  await knex.schema.dropTableIfExists('notification_templates')
  await knex.schema.dropTableIfExists('appointment_feedback')
  await knex.schema.dropTableIfExists('appointments')
  await knex.schema.dropTableIfExists('appointment_slots')
  await knex.schema.dropTableIfExists('section_capacity')
  await knex.schema.dropTableIfExists('section_schedules')
  await knex.schema.dropTableIfExists('sections')
}
