// ============================================================
// Data/AppointmentDbContext.cs
//
// EF6 Database-First DbContext for the Appointment Booking service.
//
// DATABASE-FIRST APPROACH
// -----------------------
// This file was generated by reverse-engineering the existing SQL
// Server schema.  To re-scaffold after a schema change, run:
//
//   dotnet ef dbcontext scaffold \
//     "Name=ConnectionStrings:AppointmentDb" \
//     EntityFramework.SqlServer \
//     --output-dir Models \
//     --context AppointmentDbContext \
//     --context-dir Data \
//     --force
//
// Then reconcile any naming differences against the live API
// response shapes expected by the admin panel and frontend.
// ============================================================
using AppointmentBooking.Models;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace AppointmentBooking.Data;

/// <summary>
/// EF6 DbContext for the Appointments microservice.
/// Exposes <see cref="AppointmentData"/> and
/// <see cref="AppointmentSection"/> as first-class DbSets.
/// </summary>
public class AppointmentDbContext : DbContext
{
    // ----------------------------------------------------------------
    // Constructor
    // ----------------------------------------------------------------

    /// <summary>
    /// Initialises the context using the named connection string
    /// "AppointmentDb" from appsettings.json.
    /// The base DbContext constructor resolves this via the
    /// standard EF6 connection-string lookup.
    /// </summary>
    public AppointmentDbContext(string connectionString)
        : base(connectionString)
    {
        // Disable lazy loading to prevent N+1 query issues on
        // navigation properties when serialising JSON responses.
        Configuration.LazyLoadingEnabled = false;

        // Disable proxy creation for the same serialisation reason.
        Configuration.ProxyCreationEnabled = false;
    }

    // ----------------------------------------------------------------
    // DbSets (one per database table)
    // ----------------------------------------------------------------

    /// <summary>
    /// Appointment booking records.
    /// Maps to the <c>AppointmentData</c> table in SQL Server.
    /// </summary>
    public DbSet<AppointmentData> AppointmentData { get; set; } = null!;

    /// <summary>
    /// Section / service category lookup (Kitchen, Wardrobe, …).
    /// Maps to the <c>AppointmentSection</c> table in SQL Server.
    /// </summary>
    public DbSet<AppointmentSection> AppointmentSections { get; set; } = null!;

    // ----------------------------------------------------------------
    // Model configuration (Database-First conventions)
    // ----------------------------------------------------------------

    /// <inheritdoc />
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        // Remove EF6's default pluralisation convention so that table
        // names match the SQL Server schema exactly (e.g. "AppointmentData"
        // not "AppointmentDatas").
        modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

        // ---- AppointmentData table ----
        modelBuilder.Entity<AppointmentData>()
            .HasKey(a => a.Id);

        modelBuilder.Entity<AppointmentData>()
            .Property(a => a.Status)
            .HasMaxLength(50)
            .HasColumnName("Status");

        // ---- AppointmentSection table ----
        modelBuilder.Entity<AppointmentSection>()
            .HasKey(s => s.Id);

        // One AppointmentSection has many AppointmentData rows.
        // The FK column in AppointmentData is "AppointmentFor" (string),
        // which stores the section name rather than the section ID.
        // This is a denormalised design from the live API; we preserve it
        // for backward compatibility with existing frontend consumers.
        modelBuilder.Entity<AppointmentSection>()
            .HasMany(s => s.Appointments)
            .WithOptional()
            .Map(m => m.MapKey("AppointmentFor"));

        base.OnModelCreating(modelBuilder);
    }
}
